dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: T2gIrTvjR1oJsD8610mncMqMnJwyvhAVdv6VGpnN5B+p8ykpKSHfWJ7Adc5R9AQeX7eGpDZnumlxypKVl2RvD4fJwULTluCtRYEfNVNaoEOEhLBfZYpp0T4j+qj4k8W9zB2PeSx9TYzO5o9Oawi856jHDiIL5wy4/fP9pwHdrP8CZ3Xnu4m0AeTxb39IAckYpe/B4KV8w4bQVvVz8T6hMPI7JhXtin7Ty2k9j2E/uE/TRFjuEWdVzcqw7hPSvrZzO4s3MoJNTnS/d7DyKaFBM8+WKdX9kSMAaOTIeQue7vWcWxWIA9VSMxZtEFGXIb56HoIc1XTtEzkZnhuKtrWrpvCPmeKWLHGGTK8JMT3diT+7a1spK3aBKSlh5A76qy3AHikzkYnk1cZP60Q0SR95PwUKQEkKIT+jqhdijrX+P8wTpU0tuMF3BbmeZuJU7LbEN57V5Z7HWwTAzFCKrbFK7uCs6PoC4NSVYeENC8hYWOdXZ2rGgHxQYrF6AaC0aovgBHu++LS3RLWyIJOgqXz3eXd0EgxoV5RfvrnsA7ybimby2u5c3L33fYndvgQh1sEWj8LwPxK2Cjf0zW0kaHsBbnb7CNbSbFkTYLl1A2zpFK2QlHQi4AGiwxYm0FK42Mo3UO5Oh8vqPsVGo8+EPx9YqiFovOOn7/H2L0F3r24vafk=
