version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
      
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:latest
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:

